name: droidenv
channels:
  - rusty1s
  - pytorch
  - open3d-admin
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-scatter
  - torchaudio
  - torchvision
  - open3d
  - pytorch
  # - cudatoolkit=11.7
  - pytorch-cuda=11.8
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - suitesparse
  - matplotlib
  - pyyaml
